parameters:

  app_name: "He!p-Center"
  full_app_name: "He!p."
  no_reply: "no-reply@khalilleo.com"

  webmasterName: "Webmaster"
  webmasterEmail: "demo@khalilleo.com"

  phoneNumber: '0163/616-5396'
  supportEmail: 'help@khalilleo.com'
  infoEmail: 'info@khalilleo.com'
  legalEmail: 'legal@khalilleo.com'

  addressStreet: 'Paul-Gerhardt-Str. 7'
  addressPlz: '74321'
  addressCity: 'Bietigheim-Bissingen'
  addressCountry: 'Deutschland'

  app_version: "1.1.3"
  
  app_author: "Khalilleo Teams"
  app_created: "2024-05-22"
  app_made_by: "khalilleo.com"